<h1>Categories</h1>

<div class=info><?= $pager->getInfo() ?> items</div>
<table class=listing_tb>
	<tr>
		<th width=200px><strong>Photo</strong></th>
		<th width=200px><strong>Name</strong>s</th>
		<th width=200px><strong>Total Products</strong></th>
		<th width=200px><strong>Total Owners</strong></th>
		<th></th>
	</tr>
	<? foreach($categories as $c){ ?>
	<tr>
		<td><img src="<?= $c->getPhoto(100) ?>" /></td>
		<td><?= $c->getName() ?></td>
		<? if( $c->countProducts() >0) { ?>
		<td><a href="<?= SITE_URL ?>products.php?cat=<?= $c->getId() ?>"> View <?= $c->countProducts() ?> Products</a></td>
		<? } else { ?>
		<td>--</td>
		<? } ?>
		
		<? if( $c->countOwners() >0) { ?>
		<td><a href="<?= SITE_URL ?>owners.php?category=<?= $c->getId() ?>"> View <?= $c->countOwners() ?> Owners </a></td>
		<? } else { ?>
		<td>--</td> 
		<? } ?>
		<? if(USER_ROLE == 'admin') { ?>
		<td width=200px>
			<a href="<?= SITE_URL ?>categories.php?del=<?= $c->getId() ?>">Delete</a> | 
			<a href="<?= SITE_URL ?>addCategory.php?edit=<?= $c->getId() ?>">Edit</a>
		</td>
		<? }else { ?>
		<td></td>
		<? } ?>
	</tr>
	<? } ?>	
</table>
<?= $pager->getLinks() ?>