			</div>
			<!-- end div content -->
			<div class=footer>
				<div class=links>
					<a href="index.php">Home Page</a> |  
					<a href="aboutus.php">About Us</a> |  
					<a href="categories.php">Product Categories</a> |  
					<a href="contactus.php">Contact Us</a>
				</div>
				<div class=address>
					© 2013 Shopping Hub. All Rights Reserved<br>Designed by 
					<a href="http://ahmadalibaloch.wordpress.com/" target="_blank">Ahmad Ali</a>
				</div>
			</div>
		</div>
		<!-- end div body -->
	</body>
</html>