<h1>Products</h1>

<? if ($search) { ?>
<div class=info>
	Searching for " <span class=searching><?= $search ?></span> " in products |
	<a href="<?= SITE_URL.'products.php?search=all' ?>">View all products</a>
</div>	
<? } ?>

<? if ($category_name) { ?>
<div class=info>
	Showing products for <?= $category_name ?> |
	<a href="<?= SITE_URL.'products.php?search=all' ?>">View all products</a>
</div>	
<? } ?>

<div class=info><?= $pager->getInfo() ?> products</div>
<table class=listing_tb>	
	<tr>
		<th></th>
		<th><strong>Name</strong>s</th>
		<th><strong>Unit Price</strong>s</th>
		<th><strong>Stock Count</strong></th>
		<th><strong>Category</strong></th>
		<th><strong>Owner</strong></th>
		<th><strong>Operations</strong></th>
	</tr>
	<? foreach($products as $p){ ?>
	<tr>
		<td>
			<? if($p->getPhoto()) {?>
			<image src="<?= $p->getPhoto(150) ?>" height=150/>
			<? } else { ?>
			No Image
			<? } ?>
		</td>
		<td><?= $p->getName() ?></td>
		<td><?= $p->getPrice() ?> Rs.</td>
		<td><?= $p->getQuantity() ?></td>
		<td><?= $p->getCategory()->getName() ?></td>
		<td><?= $p->getOwner()->getName() ?></td>
		<td>
			<a href="<?= SITE_URL ?>product.php?id=<?= $p->getId() ?>">View Details</a>
			<? if(USER_ROLE == 'owner' && $p->getOwner()->getUserId() == USER_ID) { ?>
			| <a href="<?= SITE_URL ?>addProduct.php?edit=<?= $p->getId() ?>">Edit</a> | 
			<a href="<?= SITE_URL ?>products.php?del=<?= $p->getId() ?>">Delete</a>
			<? } ?>
		</td>
	</tr>
	<? } ?>
</table>
<?= $pager->getLinks() ?>